[build-system]
requires = [
    "pip-tools>=6.3",
    "setuptools>=57.4",
    "wheel>=0.37"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini-options]
minversion = "6.2"
adopts = "-ra"
testpaths = [
  "tests"
]
