[build-system]
requires = [
    "setuptools>=57.4",
    "wheel>=0.37"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "-ra"
testpaths = [
  "tests"
]
